### ISSUE TITLE
Cannot change CMake build type

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#15]
Some earlier change hard-coded the `CMAKE_BUILD_TYPE` so now it cannot be selected from the command line.
https://github.com/nasa/HDTN/blob/9f543f2a788ee449129f9ad735ac4acaee0903ff/CMakeLists.txt#L7

This should be removed or at least guarded somehow so that setting from the cmake command still works.

**Comment by briantomko** [comment]
This issue has been resolved with the merge of branch '75-cmake-build-type' into 'master'
If the user specifies -DCMAKE_BUILD_TYPE on the command line, take their definition and dump it in the cache along with proper documentation, otherwise set CMAKE_BUILD_TYPE to Release by default.  Print warning if user selects Debug mode.
