### ISSUE TITLE
Mark entire class as exported for convenience

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#25]
Currently there are many classes that have all of their public functions marked with the `LTP_LIB_EXPORT` macro (or similar for other libraries). It is possible to mark the entire class as exported to save editing whenever functions are added, similar to
```c++
class LTP_LIB_EXPORT LtpUdpEngineManager { ... };
```

This is just a suggestion to ease maintenance, it wouldn't affect the result of function symbols being exported in the libraries.

**Comment by briantomko** [comment]
Unfortunately since HDTN doesn't use the "Pointer to implementation" or "pImpl" C++ programming technique, and since HDTN's classes contain classes of the standard template library, on Windows this is a problem as the "EXPORT" will try to export all those classes resulting in numerous warnings/errors.  Hence, that is why we try to only EXPORT the public member functions.
