### ISSUE TITLE
Use modern CMake for library dependencies

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#9]
Especially for boost, which is split into many components, using [dependencies as targets](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/#model-dependencies-with-target_link_libraries) makes it much easier and cleaner to manage a multi-platform library like HDTN.

Instead of having to manually use variables like `Boost_LIBRARIES` and `Boost_INCLUDE_DIRS` in the right places, use the pre-existing targets like `Boost::program_options` as link requirements for specific HDTN libraries. This doesn't affect build content or speed, only for maintainability. I can post in comments some examples of using this. It also removes conditionals when complex dependencies are used.

Using this technique also then makes the include and link properties transitive from dependencies to built libraries, simplifying the users of the HDTN libraries.

**Comment by briantomko** [comment]
This issue has been resolved with the merge of branch '77-modernize-cmake' into 'master'.

In addition, package config information has been exported to the installation (`install_root/lib/cmake`).  There is an example in `tests/unit_tests_import_installation/CMakeLists.txt` which is a copy of the regular `tests/unit_tests/CMakeLists.txt` except that the former uses the find_package package config information from the `install_root/lib/cmake` directory.

In addition, targets are used for Boost and OpenSsl dependencies instead of manually using variables.

In addition, there is no more setting of` CMAKE_CXX_FLAGS`, but rather the `target_compile_options `is now used.

The `cmake_minimum_required `is now set to VERSION 3.12 because of the usage of generator functions such as `$<TARGET_NAME_IF_EXISTS:tgt>` which is new in version 3.12.

There has been plenty of cleanup in the various CMakeLists.txt files.
